Repository joanmdrs/sigcli, pull requests merged in 2022-06, with the labels that each got.

#115 Feat/issue87
  client/src/App.js
  client/src/components/Box/Box.js
  client/src/components/Forms /BaseForm/BaseForm.css
  client/src/components/Forms /BaseForm/BaseForm.js
  client/src/components/Forms /FormExam/FormExam.js
  client/src/components/Forms /FormRecepcionist/FormRecepcionist.js
  client/src/components/Forms /GroupButtons/GroupButtons.css
  client/src/components/Forms /GroupButtons/GroupButtons.js
  client/src/components/Forms /TextArea/TextArea.css
  client/src/components/Forms /TextArea/TextArea.js
  client/src/components/Header/Header.css
  client/src/components/Header/Header.js
  client/src/components/HeaderExam/HeaderExam.js
  client/src/components/ListExam/ListExam.js
  client/src/components/Listing/ListRecepcionist/ListRecepcionist.css
  client/src/components/Listing/ListRecepcionist/ListRecepcionist.js
  client/src/components/Search/Search.css
  client/src/components/Search/Search.js
  client/src/pages/Doctor/Doctor.js
  client/src/pages/Exam/Exam.js
  client/src/pages/Patient/Patient.css
  client/src/pages/Recepcionist/Recepcionist.css
  client/src/pages/Recepcionist/Recepcionist.js
  client/src/routes.js
  client/src/services/AppointmentServices.js
  client/src/services/ExamServices.js
  client/src/services/RecepcionistServices.js
  server/controllers/recepcionistController.js
  server/package-lock.json
  server/package.json
  server/prisma/schema.prisma
  server/repositories/appointmentRepository.js
  server/repositories/doctorRepository.js
  server/repositories/examRepository.js
  server/repositories/recepcionistRepository.js
  server/routes/recepcionistRoutes.js
Labels: enhancement

#117 Feat/114
  client/src/pages/Exam/Exam.js
  client/src/pages/Login/Login.css
  client/src/pages/Login/Login.js
  client/src/routes.js
Labels: enhancement

#127 Refatorando os alerts no crud de consulta #89
  client/src/pages/Appointment/Appointment.js
  client/src/services/AppointmentServices.js
Labels: refector

#128 Refatorando as rotas para o plural #96
  client/src/components/Nav/Nav.js
  client/src/routes.js
Labels: refector

#129 Implementando a filtragem por crm #123
  client/src/components/Header/Header.css
  client/src/components/Search/Search.js
  client/src/pages/Doctor/Doctor.js
  client/src/pages/Recepcionist/Recepcionist.js
  client/src/services/DoctorServices.js
  server/controllers/doctorController.js
  server/repositories/doctorRepository.js
  server/routes/doctorRoutes.js
Labels: enhancement

#143 Refector/issue81
  client/src/components/FormAppointment/FormAppointment.js
  client/src/pages/Appointment/Appointment.js
  client/src/services/AppointmentServices.js
  server/controllers/appointmentController.js
  server/prisma/schema.prisma
  server/repositories/appointmentRepository.js
  server/service/validations.js
Labels: refector

#144 Test/issue139
  client/babel.config.js
  client/package-lock.json
  client/package.json
  client/src/components/Box/Box.css
  client/src/components/Box/Box.js
  client/src/components/Header/Header.js
  client/src/pages/Exam/Exam.js
  client/src/pages/Exam/Exam.test.js
  client/src/pages/Exam/__snapshots__/Exam.test.js.snap
  client/src/routes.js
Labels: test

#146 Feat/issue83 - Inserindo Validações de Exame
  server/controllers/examController.js
Labels: refector

#147 Feat/issue101 - Documentando UserStory Manter Pagamento
  docs/doc-userstories.md
  docs/doc-visao.md
Labels: documentation

#151 test: checa se está listando o doutor corretamente #138
  client/src/components/ListDoctor/ListDoctor.test.js
Labels: test

#153 Feat/issue140 - Implementar teste unitário Appointment
  client/src/components/ListAppointment/ListAppointment.test.js
Labels: test

#166 Implementando o cálculo de PF para o CRUD de médico #154
  docs/doc-pontosfuncao.md
Labels: documentation
