Repository joanmdrs/sigcli, pull requests merged in 2022-07, with the labels that each got.

#185 Refactor/issue184 - Removendo alguns code smells
  client/src/components/HeaderAppointment/HeaderAppointment.js
  client/src/pages/Appointment/Appointment.js
  client/src/pages/Doctor/Doctor.js
  client/src/pages/Exam/Exam.js
  client/src/pages/Login/Login.js
  client/src/pages/Patient/Patient.js
  client/src/pages/Recepcionist/Recepcionist.js
  client/src/services/AppointmentServices.js
  client/src/services/DoctorServices.js
  client/src/services/ExamServices.js
  client/src/services/RecepcionistServices.js
  client/src/services/patientServices.js
Labels: refactor

#191 Test/issue176 - Testes unitários de Doctor
  client/src/components/Forms/FormDoctor/FormDoctor.test.js
  client/src/components/ListDoctor/ListDoctor.test.js
Labels: test

#192 Doc/issue178
  docs/doc-aceitacao.md
Labels: documentation

#193 Implementando os testes de aceitação de manter exame #180
  docs/doc-aceitacao.md
Labels: documentation
